Use absolute imports to avoid conflict with urllib3
In urllib3/connectionpool.py is:
from queue import LifoQueue, Empty, Full

This is causing problems when openerp-connector-worker is initialized:
 File "connector/connector/queue/__init__.py", line 22, in <module>
    from . import model
  File "connector/connector/queue/model.py", line 28, in <module>
    from .job import STATES, DONE, PENDING, OpenERPJobStorage, JOB_REGISTRY
  File "/connector/connector/queue/job.py", line 33, in <module>
    from ..exception import (NotReadableJobError,
ValueError: Attempted relative import beyond toplevel package

This commit fixes this behaviour by using absolute imports in queue/model.py and queue/job.py